name: Ejercicio3

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Codigo
      uses: actions/checkout@v2
    - uses: actions/setup-node@v3
    - name: Instalar dependencias
      run: npm ci
    - name: Ejecutar Test
      run: npm test
    - name: Cypress
      uses: cypress-io/github-action@v5
      with:
        browser: Chrome
        parallel: true
        record: true
        