name: Ejercicio2

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'hagman-front'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: hangman-api/package-lock.json
      - name: Build Docker Image
        env:
          TOKEN_PASSWORD: ${{ secrets.TOKEN_PASSWORD }}
        run: |
          npm ci 
          npm run build --if-present
          docker login ghcr.io -u hugonico7 -p ${TOKEN_PASSWORD}
